_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 117d0aab-78ee-4bec-ba47-a6f608d1c40b
name: 'Employee Management application'
mail: admin@example.com
slogan: ''
page:
  403: /node/2
  404: /node/1
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
